default_url_options:
  development: http://localhost:5000
  test:        http://localhost:5000
  production:  http://example.com
  
singly_api_base: https://api.singly.com

trigger_words:
  -  hopeless
  -  sad
  -  disappointed
  -  disappointing
  -  tragedy
  -  inconsolable
  -  devastated
  -  anguished
  -  anguish
  -  letdown
  -  undone
  -  depressed
  -  dismal
  -  somber
  -  tragic
  -  mourning
  -  tearful
  -  harrowing
  -  heart-breaking
  -  terrible
  -  crying
  -  sobbing
  -  lonely
  -  abandoned
  -  abandonment
  -  inadequate
  -  mourn
  -  dejected
  -  suicidal
